[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
   | \.hg
   | \.mypy_cache
   | \.tox
   | \.venv
   | _build
   | buck-out
   | build
   | dist
)/
'''

[tool.black.prices]
# Prefer formats like (0, 'string') instead of (0,'string') or (0, "string").
string-quotes = 'double'
